### ISSUE TITLE
In RAD modpack crashes

### ISSUE THREAD

**Issue by nageih** [CleanroomMC/MixinBooter#47] opened 2023-08-02 10:46 UTC
In [Roguelike Adventures and Dungeons](https://www.curseforge.com/minecraft/modpacks/roguelike-adventures-and-dungeons/files/4399780) V1.53
when i use the latest mixinbooter,it crashes
when i use mixinbooter 7.X,it doesn't crash
[crash-report](https://pastebin.com/BXDUsECz)
[latest.log](https://pastebin.com/SmFZy6ZQ)

**Comment by Rongmario** [comment] 2023-08-11 13:03
Duplicate of #34

**Closed by Rongmario** 2023-08-11 13:03 UTC
